apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: telemedicine
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # admin
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29kYjEyMw== # mongodb123
