apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
  namespace: telemedicine
data:
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres-service:5432/telemedicine?currentSchema=public'
  SPRING_DATASOURCE_USERNAME: 'postgres'
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'org.postgresql.Driver'
  SPRING_JPA_HIBERNATE_DDL_AUTO: 'validate'
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQLDialect'
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: 'public'
  SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka-service:9092'
  KAFKA_TOPIC: 'appointment.booked'
  SERVER_PORT: '8081'
