apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: telemedicine
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: appointment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: KAFKA_TOPIC
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: appointment-service-config
                  key: SERVER_PORT
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1000m'
