apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: telemedicine
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM= # postgres123
