apiVersion: v1
kind: ConfigMap
metadata:
  name: session-service-config
  namespace: telemedicine
data:
  SPRING_DATA_MONGODB_HOST: 'mongodb-service'
  SPRING_DATA_MONGODB_PORT: '27017'
  SPRING_DATA_MONGODB_DATABASE: 'telemedicine'
  SPRING_DATA_MONGODB_USERNAME: 'admin'
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: 'admin'
  SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka-service:9092'
  KAFKA_TOPIC: 'session.started'
  SERVER_PORT: '8082'
